url: https://courses.stolley.co
baseurl: /wsi/

timezone: America/Chicago

course:
  number: ITMD 467/567
  title: Web Systems Integration
  uid: wsi
  tagline: >
    A project-based course on the integration of web applications, services, and infrastructure to
    scale.
  term: Spring 2020
  # Set `days: ""` (empty string) for weekly/asynchronous classes
  days:
    - Monday
    - Wednesday
  license:
    name: Creative Commons
    url: https://creativecommons.org/licenses/by/4.0/
  instructor:
    honorific: Dr.
    name: Karl Stolley
    title: Professor
    full_title: Associate Professor of Information Technology and Management
    url: https://stolley.co/
    github: https://github.com/karlstolley/
    email: karl.stolley@gmail.com
    office_hours: >
      Office hours via Basecamp Chat or Pings on Tuesdays, 4pm to 5pm, or by appointment or chance.
      I’m always signed into Basecamp and closely monitor my notifications. Message or email any
      time—I make students a priority, and I will repond as soon as I am able.

collections_dir: syllabus

collections:
  weeks:
  projects:
  policies:
    # Rearrange the files listed here to change their order on the policies page.
    # To remove a section from the policies page, you *must* delete the file in the
    # /syllabus/_policies/ directory
    order:
      - description.md
      - goals.md
      - outcomes.md
      - objectives.md
      - books.md
      - materials.md
      - special-needs.md
      - participation.md
      - assignment-submission.md
      - late-work.md
      - grading-policy.md
      - grading-criteria.md
      - technology-policy.md
      - academic-integrity.md

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

theme: jekyll-theme-open-course

exclude:
  - backstop_data
  - backstop.json
  - exe
  - lib
  - Rakefile
  - "*.gemspec"
